var express = require('express');
var router = express.Router();
var pg = require('pg');
var conString = "pg://postgres:postgres@localhost:5432/covalent";
var client = new pg.Client(conString);
client.connect();

var express = require(‘express’);
var app = express();
var partnerships = express.Router();
partnerships.get(‘/’, function(req, res) { });
partnerships.post(‘/’, function(req, res) { });
partnerships.get(‘/:id’, function(req, res) { });
partnerships.delete(‘/:id’, function(req, res) { });
var partnerPromos = express.Router();
partnerPromos.get(‘/’, function(req, res) { });
partnerPromos.post(‘/’, function(req, res) { });
partnerPromos.get(‘/:id’, function(req, res) { });
partnerPromos.delete(‘/:id’, function(req, res) { });
module.exports = app;
